CREATE TABLE exercises (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           title VARCHAR(255) NOT NULL,
                           statement TEXT NOT NULL,
                           type VARCHAR(255) NOT NULL,
                           code_snippet TEXT,
                           CONSTRAINT pk_exercises PRIMARY KEY (id)
);

CREATE TABLE options (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         text TEXT NOT NULL,
                         is_correct BOOLEAN NOT NULL,
                         exercise_id BIGINT NOT NULL,
                         CONSTRAINT pk_options PRIMARY KEY (id)
);

ALTER TABLE options ADD CONSTRAINT FK_OPTIONS_ON_EXERCISE FOREIGN KEY (exercise_id) REFERENCES exercises (id);