CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       username VARCHAR(50) NOT NULL,
                       password VARCHAR(120) NOT NULL,
                       email VARCHAR(80) NOT NULL,
                       CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_username UNIQUE (username);
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);